{
 "title": "Arcsight SmartConnector Metrics 2",
 "description": "Arcsight SmartConnector Metrics View 2",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "connector_m",
    "label": "Connector",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\""
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$connector_m/"
   },
   {
    "name": "disks",
    "label": "Disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$connector_m/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$connector_m$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$connector_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "Connector Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$connector_m   - Queue Rate & EPS IN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"EPS_SLC\") AS \"EPS(SLC)\", LAST(\"QUEUE_RATE_SLC\") AS \"Queue Rate(SLC)\"  FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$connector_m   - Connector EPS OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$connector_m   -  Connector Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"DESTINATION_CACHE\") AS \"Destination Cache\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$connector_m  - Connector Process Aggregated CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name  -- PID $tag_pid -- PID File: $tag_pidfile  --  User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"cpu_usage\") / [[n_cpus]] FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), pid, pidfile, * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$connector_m   -  Connector - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name -- PID: $tag_pid -- PID File: $tag_pidfile -- User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"memory_rss\") FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$connector_m  - Connector - Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name -- PID: $tag_pid  -- PID File: $tag_pidfile -- User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"num_threads\") FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/)AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$connector_m  - Connector Queue Drop Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"CURRENT_DROP_COUNT\") AS \"Queue Drop Count\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregated CPU % Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$connector_m$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Load %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 18 },
     "repeat": "server_m",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "system_load1",
       "query": "SELECT ( MEAN(load1) / [[n_cpus]] ) as load_1, ( MEAN(load5) / [[n_cpus]] ) as load_5, ( MEAN(load15) / [[n_cpus]] ) as load_15 FROM \"system\" WHERE host =~ /$connector_m$/ AND $timeFilter GROUP BY time($inter), * ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Bandwidth per NIC",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 18 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) * count(\"bytes_recv\") / count(\"bytes_recv\") * 8 as \"Inbound\"  FROM \"net\" WHERE host =~ /$connector_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(mean(bytes_sent),1s) * count(\"bytes_sent\") / count(\"bytes_sent\") * 8 as \"Outbound\" FROM \"net\" WHERE host =~ /$connector_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk % Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
     "repeat": "m_server",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /$connector_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"path\" fill(none)",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used_percent" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
     "repeat": "m_server",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_path - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$connector_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Per CPU Total (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "repeat": "server_m",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Total $tag_cpu",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_user\") + mean(usage_system) + mean(usage_iowait) FROM \"cpu\" WHERE (\"host\" =~ /^$connector_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           "+ mean(usage_system) + mean(usage_iowait)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Per CPU User (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "repeat": "server_m",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "User $tag_cpu",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^$connector_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Per CPU System (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "repeat": "server_m",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "System $tag_cpu",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_system\") FROM \"cpu\" WHERE (\"host\" =~ /^$connector_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Per CPU IO Wait (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "repeat": "server_m",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "IoWait $tag_cpu",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$connector_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
       "select": [
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$connector_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connector Parameters",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"AGENT_TYPE\") AS \"Agent Type\", LAST(\"AGENT_VERSION\") AS \"Agent Version\", LAST(\"PARSER_AUP_VERSION\") AS \"Parser AUP Version\", LAST(\"PORT\") AS \"Port\", LAST(\"PROTOCOL\") AS \"Protocol\", LAST(\"IP_ADDRESS\") AS \"IP Address\", LAST(\"FORWARDER\") AS \"Forwarder\", LAST(\"FIPS_ENABLED\") AS \"FIPS Enabled\" FROM \"Z_Con_1\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter)",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Connector Statistics",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"COMMAND_RESPONSES_PROCESSED\") AS \"Commands Processed\", LAST(\"EVENTS_FILTERED_OUT\") AS \"Events Filtered Out\", LAST(\"EVENTS_FILTER_STATE\") AS \"Events Filter State\", LAST(\"EVENTS_PROCESSED\") AS \"Events Processed\", LAST(\"TRACKING_DEVICE_COUNT\") AS \"Tracking Device Count\", LAST(\"TRACKING_EVENT_COUNT\") AS \"Tracking Event Count\", LAST(\"TRACKING_EVENT_SIZE\") AS \"Tracking Event Size\" FROM \"Z_Con_1\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY host",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}