{
 "title": "Arcsight SmartConnector Metrics 3",
 "description": "Arcsight SmartConnector Metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "connector_m",
    "label": "Connector",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\""
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$connector_m/"
   },
   {
    "name": "disks",
    "label": "Disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$connector_m/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$connector_m$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$connector_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "Connector Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EPS IN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"EPS_SLC\") AS \"EPS(SLC)\", LAST(\"QUEUE_RATE_SLC\") AS \"Queue Rate(SLC)\"  FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "EPS OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"DESTINATION_CACHE\") AS \"Destination Cache\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Drop Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_AGENT_NAME $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"CURRENT_DROP_COUNT\") AS \"Queue Drop Count\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), AGENT_NAME, *",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name  -- PID $tag_pid -- PID File: $tag_pidfile  --  User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"cpu_usage\") / [[n_cpus]] FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), pid, pidfile, * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ConnMem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name -- PID: $tag_pid -- PID File: $tag_pidfile -- User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"memory_rss\") FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/) AND $timeFilter GROUP BY time($inter), * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ConnThreads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "repeat": "connector_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name -- PID: $tag_pid  -- PID File: $tag_pidfile -- User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"num_threads\") FROM \"procstat\" WHERE (\"host\" =~ /^$connector_m$/)AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}