{
 "title": "Logger Software Metrics - Multiple Instances",
 "description": "Arcsight Logger Software (Multiple Instances) Metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "logger_m",
    "label": "Logger",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\""
   },
   {
    "name": "logger_path",
    "label": "Logger Path",
    "query": "/opt/logger,/opt/loggersoft/,/opt/softlogger/"
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$logger_m$|$arcmc_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Edit the \"Logger Path\" variable if the directory where Logger software was installed is not listed",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "content": "\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logger Receiver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logger Total EPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"EPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Total Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total Events\" FROM (SELECT LAST(\"Total_Events\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY * fill(none)) GROUP BY host fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes/Sec per Receiver Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_Receiver_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"BPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter), Receiver_Type, host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logger Indexing WOS Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host  $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"ChunkID_Count\") AS \"Indexing WOS Lag\" FROM \"exec_Logger_PostgreSQL\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($__interval), host, * fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Logger Processes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logger Processes - Aggregated CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/runtime/aps.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_usage\") / [[n_cpus]] AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '[[logger_path]]current/runtime/mysql_server.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logger Processes - Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger WEB \" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/runtime/aps.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '[[logger_path]]current/runtime/mysql_server.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/runtime/aps.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_usage\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '[[logger_path]]current/runtime/mysql_server.pid') AND $timeFilter GROUP BY time($inter), host fill(none) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes - CPU I/O Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '[[logger_path]]current/runtime/aps.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '[[logger_path]]current/runtime/mysql_server.pid') AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logger Processor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Logger Processors EPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_Processor_Type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT last(\"EPS_SLC\") as \"EPS\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), \"Processor_Type\", host fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Processor Total Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total Events\" FROM (SELECT LAST(\"Total_Events\") AS \"pointer\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY * fill(none)) GROUP BY host fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Processors Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_Processor_Type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT last(\"BPS_SLC\") as \"Bytes/sec\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), \"Processor_Type\", host fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}