{
 "title": "Logger Appliance Metrics - Single Instance",
 "description": "Arcsight Logger Appliance (Single Instance) Metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "logger_m",
    "label": "Logger",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\""
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$logger_m/"
   },
   {
    "name": "disks",
    "label": "Disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$logger_m$/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$logger_m$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$logger_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_onlinecores",
     "query": "select last(\"n_cpus\") FROM \"system\" WHERE (\"host\" =~ /$logger_m$/)",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" =~ /^$logger_m$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$logger_m$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT ( MEAN(load1) / [[n_cpus]] ) as load_1, ( MEAN(load5) / [[n_cpus]] ) as load_5, ( MEAN(load15) / [[n_cpus]] ) as load_15 FROM \"system\" WHERE host =~ /$logger_m$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth per NIC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s) * count(\"bytes_recv\") / count(\"bytes_recv\") * 8 as \"Inbound\"  FROM \"net\" WHERE host =~ /$logger_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s) * count(\"bytes_sent\") / count(\"bytes_sent\") * 8 as \"Outbound\" FROM \"net\" WHERE host =~ /$logger_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk % Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "repeat": "m_server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /$logger_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"path\" fill(none)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "repeat": "m_server",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$logger_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU Total (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(usage_system) + mean(usage_iowait) FROM \"cpu\" WHERE (\"host\" =~ /^$logger_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "+ mean(usage_system) + mean(usage_iowait)"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU User (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^$logger_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU System (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_system\") FROM \"cpu\" WHERE (\"host\" =~ /^$logger_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU IO Wait (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "IoWait $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$logger_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$logger_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logger Receiver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Logger Total EPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"EPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Total Events",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 21 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total Events\" FROM (SELECT LAST(\"Total_Events\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes/sec per Receiver Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_Receiver_Type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"BPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter), Receiver_Type fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Indexing WOS Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"ChunkID_Count\") AS \"Indexing WOS Lag\" FROM \"exec_Logger_PostgreSQL\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($__interval), * fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Logger Processors Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Logger Processors EPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col $tag_Processor_Type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT last(\"EPS_SLC\") as \"EPS\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), \"Processor_Type\" fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Porcessor Total Events",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") FROM (SELECT LAST(\"Total_Events\") AS \"pointer\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Processors Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Processor_Type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT last(\"BPS_SLC\") as \"Bytes/sec\" FROM \"Logger_Processors\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), \"Processor_Type\" fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Logger Processes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Logger Processes - Aggregated CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/APS.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") / [[n_cpus]] AS \"SNMP\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/snmp.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_usage\") / [[n_cpus]] AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '/opt/data/mysql_data/Localhost_server.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logger Processes - Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/APS.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"SNMP\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/snmp.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"num_threads\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '/opt/data/mysql_data/Localhost_server.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logger Processes - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total Server Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total) FROM \"mem\" WHERE host =~ /$logger_m$/ AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReceivers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/APS.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_rss\") AS \"SNMP\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/snmp.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_usage\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '/opt/data/mysql_data/Localhost_server.pid') AND $timeFilter GROUP BY time($inter) fill(none) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes - CPU I/O Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Receivers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger WEB\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerWeb.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Servers\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerServers.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Processors\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerProcessors.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Logger Report Engine\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/logger/run/LoggerReportEngine.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"Apache\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/userdata/logs/apache/httpd.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"APS\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/APS.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"SNMP\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"pidfile\" = '/opt/arcsight/aps/run/snmp.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_time_iowait\") AS \"MySQL\" FROM \"procstat\" WHERE (\"host\" =~ /^$logger_m$/ AND \"process_name\" = 'mysqld' AND \"pidfile\" = '/opt/data/mysql_data/Localhost_server.pid') AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}