{
 "title": "TH&Logger (Single Instance) + Nodes Metrics",
 "description": "Arcsight TH Kafka & Logger Metrics + Node Metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "server_m",
    "label": "Nodes",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "logger_m",
    "label": "Logger",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "kafka_manager",
    "label": "Kafka Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$server_m/"
   },
   {
    "name": "disks",
    "label": "Disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server_m/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  { "title": "Kafka & Logger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics EPS",
   "type": "graph",
   "description": "This panel shows the default TH topics' EPS.\nUse the query \"A\" as a reference to get the EPS from a non default topic.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"EPS_th-cef\") as \"th-cef\", LAST(\"EPS_th-binary_esm\") as \"th-binary_esm\", LAST(\"EPS_th-cef-other\") as \"th-cef-other\", LAST(\"EPS_th-syslog\") as \"th-syslog\", LAST(\"EPS_th-arcsight-avro\") as \"th-arcsight-avro\", LAST(\"EPS_th-arcsight-avro-sp_metrics\") as \"th-arcsight-avro-sp_metrics\", LAST(\"EPS_th-arcsight-json-datastore\") as \"th-arcsight-json-datastore\", LAST(\"EPS__schemas\") as \"_schemas\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topics' Summed Recent Offsets",
   "type": "table",
   "description": "This panel shows the defaults topics' summed recent offsets. Use the query \"A\" as a reference to get the \"Summed Recent Offset\"from  a non default topic.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"TO_th-cef\") as \"th-cef\", LAST(\"TO_th-binary_esm\") as \"th-binary_esm\", LAST(\"TO_th-arcsight-avro\") as \"th-arcsight-avro\", LAST(\"TO_th-cef-other\") as \"th-cef-other\", LAST(\"TO_th-syslog\") as \"th-syslog\", LAST(\"TO___consumer_offsets\") as \"__consumer_offsets\", LAST(\"TO__schemas\") as \"_schemas\", LAST(\"TO_th-arcsight-avro-sp_metrics\") as \"th-arcsight-avro-sp_metrics\", LAST(\"TO_th-arcsight-json-datastore\") as \"th-arcsight-json-datastore\"FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumers' Lag",
   "type": "graph",
   "description": "This panel shows the consumers' lag.\nUse the query \"A\" as a reference to get a specific consumer's lag.  For now this panel only shows metrics from consumers that DON'T have any space in their names, for example a consumer with the name \"consumer_01\" is valid but \"consumer 01\" is not.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"com.arcsight.th.CEF_TEXT_ROUTING_1__LAG__Consuming_From__th-cef\") as \"CEF_TEXT_ROUTING_1  Consuming From  th-cef\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"metrics-processor__LAG__Consuming_From__th-arcsight-avro-sp_metrics\") as \"metrics-processor  Consuming From  th-arcsight-avro-sp_metrics\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"com.arcsight.th.C2A__LAG__Consuming_From__th-cef\") as \"com.arcsight.th.C2A Consuming From  th-cef\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brokers on KM Over Time",
   "type": "graph",
   "description": "This panel shows how many brokers are shown in the Kafka Manager.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"Brokers_on_KM\") as \"Brokers on KM\"FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logger Total EPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"EPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Logger Total Events",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT SUM(\"pointer\") as \"Total Events\" FROM (SELECT LAST(\"Total_Events\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes/Sec per Receivers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_Receiver_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"pointer\") as \"Total EPS\" FROM (SELECT last(\"BPS_SLC\") AS \"pointer\" FROM \"Logger_Receivers\" WHERE (\"host\" =~ /^$logger_m$/) AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter), Receiver_Type fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$server_m",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 15 },
   "repeat": "server_m",
   "content": "\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 16 },
   "repeat": "server_m",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_onlinecores",
     "query": "select last(\"n_cpus\") FROM \"system\" WHERE (\"host\" =~ /$server_m$/)",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server_m$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per CPU Total (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(usage_system) + mean(usage_iowait) FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "+ mean(usage_system) + mean(usage_iowait)"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU User (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU System (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_system\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\"",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU IO Wait (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "IoWait $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\"",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load ($n_cpus CPUs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as load_1,mean(load5) as load_5,mean(load15) as load_15 FROM \"system\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT ( MEAN(load1) / [[n_cpus]] ) as load_1, ( MEAN(load5) / [[n_cpus]] ) as load_5, ( MEAN(load15) / [[n_cpus]] ) as load_15 FROM \"system\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth per NIC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"Inbound\"  FROM \"net\" WHERE host =~ /$server_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"Outbound\" FROM \"net\" WHERE host =~ /$server_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk % Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /$server_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}