{
 "title": "TH, ESM & Vertica (Single Instance) + Node Metrics",
 "description": "Arcsight TH Kafka, Logger and Vertica Metrics + Node Metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "Arcsight",
  "Vertica"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "server_m",
    "label": "Nodes",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "esm_m",
    "label": "ESM",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "kafka_manager",
    "label": "Kafka Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "Vertica", "label": "Vertica", "query": "vertica-grafana-datasource" },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$server_m/"
   },
   {
    "name": "disks",
    "label": "Disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server_m/"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   },
   {
    "name": "con_log",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "con_th",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Connector Sending to TH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 1 },
     "repeat": "con_th",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_th$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_th$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_th$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 14.399999999999999, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_th$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_th$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors Sending to ESM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 2 },
     "repeat": "con_log",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_log$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_log$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_log$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 14.399999999999999, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_log$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "EPS OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_AGENT_NAME $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "tail_eps",
       "query": "SELECT LAST(\"DESTINATION_THROUGHPUT\") AS \"Destination Throughput\" FROM \"Z_Conn_2\" WHERE (\"host\" =~ /^$con_log$/) AND $timeFilter GROUP BY time(60s), AGENT_NAME, *",
       "select": [
        [
         { "params": [ "eps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "ESM, Kafka and Vertica Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "ESM EPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "locale", "label": "EPS" }
   ],
   "targets": [
    {
     "alias": "EPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_eps",
     "query": "SELECT LAST(\"eps\") FROM \"tail_eps_esm\" WHERE (\"host\" =~ /^$esm_m$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" }
     ]
    }
   ]
  },
  {
   "title": "Topics EPS",
   "type": "graph",
   "description": "This panel shows the default TH topics' EPS.\nUse the query \"A\" as a reference to get the EPS from a non default topic.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"EPS_th-cef\") as \"th-cef\", LAST(\"EPS_th-arcsight-avro\") as \"th-arcsight-avro\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /n15-214-141-h236.arcsight.com/ AND $timeFilter GROUP BY time(5s), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertica EPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(frame_start),\r\nSUM(partition_messages)/(extract(epoch from max(batch_end))-extract(epoch from min(batch_start))) AS EPS\r\nFROM investigation_scheduler.stream_microbatch_history\r\nWHERE \r\n  $__timeFilter(frame_start)\r\nGROUP BY frame_start \r\nORDER BY frame_start ASC;"
    }
   ]
  },
  {
   "title": "Manager Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(mean(\"cpu_time_system\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"pidfile\" = '/opt/arcsight/var/tmp/manager/default/server.pid') AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumers' Lag",
   "type": "graph",
   "description": "This panel shows the consumers' lag.\nUse the query \"A\" as a reference to get a specific consumer's lag.  For now this panel only shows metrics from consumers that DON'T have any space in their names, for example a consumer with the name \"consumer_01\" is valid but \"consumer 01\" is not.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"vertica-investigate__LAG__Consuming_From__th-arcsight-avro\") as \"vertica-investigate Consuming From th-arcsight-avro\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"com.arcsight.th.C2A__LAG__Consuming_From__th-cef\") as \"com.arcsight.th.C2A Consuming From  th-cef\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Logger_Consumer__LAG__Consuming_From__th-cef\") as \"Logger_Consumer Consuming From  th-cef\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertica Scheduler Batch States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(frame_start),\r\nSUM(case when end_reason='END_OF_STREAM' then 1 else 0 end) AS EOS,\r\nSUM(case when end_reason='DEADLINE' then 1 else 0 end) AS DL,\r\nSUM(case when end_reason='NETWORK_ISSUE' then 1 else 0 end) AS NWI \r\nFROM investigation_scheduler.stream_microbatch_history\r\nWHERE \r\n  $__timeFilter(frame_start)\r\nGROUP BY frame_start \r\nORDER BY frame_start ASC;"
    }
   ]
  },
  {
   "title": "ESM MySQL Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "MySQL $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT MEAN(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(MEAN(\"cpu_time_iowait\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"process_name\" = 'mysqld') AND $timeFilter GROUP BY time($inter)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Cores Used" ], "type": "alias" }
      ],
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IO Wait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "mysqld" }
     ]
    }
   ]
  },
  {
   "title": "Events Difference Between th-cef & th-arcsight-avro",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "locale", "label": "Events" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"EPS_th-cef\") - LAST(\"EPS_th-arcsight-avro\") as \"Events Difference\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertica - Duration & Time Between Starts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n    $__time(frame_start),\r\nextract(epoch from frame_start-prev_frame_start) as GAP\r\nfrom \r\n(select \r\nframe_start,\r\nLAG(frame_start,1) over (partition by source_cluster order by frame_start asc) as prev_frame_start\r\nfrom \r\n(select \r\nsource_cluster, \r\nframe_start \r\nfrom investigation_scheduler.stream_microbatch_history\r\n) A \r\ngroup by source_cluster, frame_start order by frame_start asc\r\n) B \r\nWHERE \r\n  $__timeFilter(frame_start) \r\ngroup by frame_start, gap\r\norder by frame_start asc;"
    },
    {
     "rawSql": "SELECT\r\n  $__time(frame_start),\r\n(extract(epoch from max(batch_end))-extract(epoch from min(batch_start))) AS Duration\r\nFROM investigation_scheduler.stream_microbatch_history\r\nWHERE \r\n  $__timeFilter(frame_start)\r\nGROUP BY frame_start\r\nORDER BY frame_start ASC;"
    }
   ]
  },
  {
   "title": "ESM PostgreSQL Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PgSQL $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat_esm",
     "query": "SELECT mean(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(mean(\"cpu_time_iowait\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"process_name\" = 'postmaster') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Cores Used" ], "type": "alias" }
      ],
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IO Wait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "postmaster" }
     ]
    },
    {
     "alias": "PgSQL Stats $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat_esm",
     "query": "SELECT mean(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(mean(\"cpu_time_iowait\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"pidfile\" = '/opt/arcsight/esm_monitor_metrics/monitor/postgres_stats_collector_process.pid') AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Cores Used" ], "type": "alias" }
      ],
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IO Wait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" },
      {
       "condition": "AND",
       "key": "pidfile",
       "operator": "=",
       "value": "/opt/arcsight/metrics/postgres_stats_collector_process.pid"
      }
     ]
    },
    {
     "alias": "PgSQL Wal Writer $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat_esm",
     "query": "SELECT mean(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(mean(\"cpu_time_iowait\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"pidfile\" = '/opt/arcsight/esm_monitor_metrics/monitor/postgres_wal_writer_process.pid') AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Cores Used" ], "type": "alias" }
      ],
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IO Wait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" },
      {
       "condition": "AND",
       "key": "pidfile",
       "operator": "=",
       "value": "/opt/arcsight/metrics/postgres_wal_writer_process.pid"
      }
     ]
    },
    {
     "alias": "PgSQL Writer $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat_esm",
     "query": "SELECT mean(\"cpu_usage\")  / 100 AS \"Cores Used\", mean(\"num_threads\") AS \"Threads\", non_negative_derivative(mean(\"cpu_time_iowait\"), 1s) AS \"IO Wait\" FROM \"procstat_esm\" WHERE (\"host\" =~ /^$esm_m$/ AND \"pidfile\" = '/opt/arcsight/esm_monitor_metrics/monitor/postgres_writer_process.pid') AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Cores Used" ], "type": "alias" }
      ],
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Threads" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_time_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IO Wait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$esm_m$/" },
      {
       "condition": "AND",
       "key": "pidfile",
       "operator": "=",
       "value": "/opt/arcsight/metrics/postgres_writer_process.pid"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Parameters",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\na.id,a.microbatch, a.max_parallelism, b.source,b.partitions, c.cluster\nFROM\ninvestigation_scheduler.stream_microbatches a , investigation_scheduler.stream_sources b, investigation_scheduler.stream_clusters c\nWHERE\na.id=b.id and b.id=c.id;"
    }
   ]
  },
  {
   "title": "Topics' Summed Recent Offsets",
   "type": "graph",
   "description": "This panel shows the defaults topics' summed recent offsets. Use the query \"A\" as a reference to get the \"Summed Recent Offset\"from  a non default topic.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Offsets" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"TO_th-cef\") as \"th-cef\", LAST(\"TO_th-arcsight-avro\") as \"th-arcsight-avro\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/ AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topics Total Size Across All Nodes",
   "type": "graph",
   "description": "To get the information of the th-cef topic size the query needs to be edited by replacing \"worker_hostname\" with the TH worker hostnames.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"pointer\") as \"Total th-cef size\" FROM (SELECT last(\"th-cef_Topic_Size\") as \"pointer\" FROM \"exec_tests\" WHERE \"host\" =~/^$server_m$/ AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"pointer\") as \"Total th-arcsight-avro size\" FROM (SELECT last(\"th-arcsight-avro_Topic_Size\") as \"pointer\" FROM \"exec_tests\" WHERE \"host\" =~/^$server_m$/ AND $timeFilter GROUP BY time($inter), * fill(none)) GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topics' Partitions",
   "type": "table",
   "description": "This panel shows the defaults topics' partitions. Use the query \"A\" as a reference to get the mentioned metric for a specific topic.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"TP_th-cef\") as \"th-cef\", LAST(\"TP_th-binary_esm\") as \"th-binary_esm\", LAST(\"TP_th-cef-other\") as \"th-cef-other\", LAST(\"TP_th-syslog\") as \"th-syslog\", LAST(\"TP_th-arcsight-avro\") as \"th-arcsight-avro\", LAST(\"TP___consumer_offsets\") as \"__consumer_offsets\", LAST(\"TP__schemas\") as \"_schemas\", LAST(\"TP_th-arcsight-avro-sp_metrics\") as \"th-arcsight-avro-sp_metrics\", LAST(\"TP_th-arcsight-json-datastore\") as \"th-arcsight-json-datastore\" FROM \"exec_Arcsight_TH_KafkaMgr_Topic_Metrics\" WHERE \"host\" =~ /$kafka_manager$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "$server_m",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "server_m",
   "content": "\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "repeat": "server_m",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_onlinecores",
     "query": "select last(\"n_cpus\") FROM \"system\" WHERE (\"host\" =~ /$server_m$/)",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server_m$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per CPU Total (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Total $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") + mean(usage_system) + mean(usage_iowait) FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "+ mean(usage_system) + mean(usage_iowait)"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU User (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU System (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_system\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Per CPU IO Wait (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "IoWait $tag_cpu",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$server_m$/ AND \"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($inter), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "!=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load ($n_cpus CPUs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as load_1,mean(load5) as load_5,mean(load15) as load_15 FROM \"system\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT ( MEAN(load1) / [[n_cpus]] ) as load_1, ( MEAN(load5) / [[n_cpus]] ) as load_5, ( MEAN(load15) / [[n_cpus]] ) as load_15 FROM \"system\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter), host fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth per NIC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"Inbound\"  FROM \"net\" WHERE host =~ /$server_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"Outbound\" FROM \"net\" WHERE host =~ /$server_m$/ AND interface =~ /$nic/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/  AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server_m$/ AND \"name\" =~ /$disks$/ AND $timeFilter GROUP BY time($inter), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"path\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk % Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /$server_m$/ AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($inter), \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}