{
 "title": "Linux OS Processes Metrics",
 "description": "Displays the aggregated % CPU usage, memory and threads from Linux OS",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "server_m",
    "label": "Nodes",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\""
   },
   {
    "name": "n_cpus",
    "query": "SELECT LAST(\"n_cpus\") FROM \"system\" WHERE host =~ /$server_m/"
   },
   {
    "name": "disks",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "nic",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server_m$/"
   },
   {
    "name": "processes",
    "label": "Processes",
    "query": "SHOW TAG VALUES FROM \"procstat\" WITH KEY = \"process_name\""
   },
   {
    "name": "user",
    "label": "User",
    "query": "SHOW TAG VALUES FROM \"procstat\" WITH KEY = \"user\""
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU(s)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "server_m",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exec_onlinecores",
     "query": "select last(\"n_cpus\") FROM \"system\" WHERE (\"host\" =~ /$server_m$/)",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "$server_m  - Processes Aggregated CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name  ---  PID $tag_pid --- PID File: $tag_pidfile  ---  User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"cpu_usage\") / [[n_cpus]] FROM \"procstat\" WHERE (\"host\" =~ /^$server_m$/ AND \"process_name\" =~ /^$processes$/ AND \"user\" =~ /^$user$/) AND $timeFilter GROUP BY time($inter), pid, *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server_m Processes  Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total Server Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(total) FROM \"mem\" WHERE host =~ /$server_m$/ AND $timeFilter GROUP BY time($inter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Process Name: $tag_process_name  ---  PID $tag_pid --- PID File: $tag_pidfile  ---  User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"memory_rss\") FROM \"procstat\" WHERE (\"host\" =~ /^$server_m$/ AND \"process_name\" =~ /^$processes$/ AND \"user\" =~ /^$user$/) AND $timeFilter GROUP BY time($inter), * ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server_m Processes - Number of Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "repeat": "server_m",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Process Name: $tag_process_name  ---  PID $tag_pid --- PID File: $tag_pidfile  ---  User: $tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"num_threads\") FROM \"procstat\" WHERE (\"host\" =~ /^$server_m$/ AND \"process_name\" =~ /^$processes$/ AND \"user\" =~ /^$user$/)AND $timeFilter GROUP BY time($inter), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}